server:
  port: 9988
spring:
  application:
    name: sample-project-graphql-only
  datasource:
    url: jdbc:h2:mem:testdb1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
    defer-datasource-initialization: true